# Generated by Django 5.1.7 on 2025-03-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_update_prices'),
        ('store', '0004_auto_20210529_1741'),
    ]

    operations = [
    ]
